export CDPATH=$CDPATH:~/Program/work:~/Program/pet_projects
export NLS_DATE_FORMAT="DD-MON-YYYY HH24:MI:SS"

export PATH="/opt/homebrew/bin:/Users/chiffa/.tsh:$PATH"
export HOMEBREW_NO_EMOJI=True
export HOMEBREW_NO_AUTO_UPDATE=1

export GOPATH=~/.go
export GOMODCACHE="$GOPATH/pkg/mod"
export GOBIN="$GOPATH/bin"
export PATH="$GOBIN:$PATH"

# Added by OrbStack: command-line tools and integration
source ~/.orbstack/shell/init.zsh 2>/dev/null || :

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

if [ -f '/Users/chiffa/.ncp/path.bash.inc' ]; then source '/Users/chiffa/.ncp/path.bash.inc'; fi
# completions are to heavy
# if [ -f '/Users/chiffa/.ncp/completion.zsh.inc' ]; then source '/Users/chiffa/.ncp/completion.zsh.inc'; fi

if [ -f '/Users/chiffa/.ycp/path.bash.inc' ]; then source '/Users/chiffa/.ycp/path.bash.inc'; fi

export PATH=$PATH:/Users/chiffa/.npc/bin
