export CDPATH=$CDPATH:~/Program/work:~/Program/pet_projects
export NLS_DATE_FORMAT="DD-MON-YYYY HH24:MI:SS"

export PATH="/opt/homebrew/bin:$PATH"
export HOMEBREW_NO_EMOJI=True

# Added by OrbStack: command-line tools and integration
source ~/.orbstack/shell/init.zsh 2>/dev/null || :
