export CDPATH=$CDPATH:~/Program/work:~/Program/pet_projects
export NLS_DATE_FORMAT="DD-MON-YYYY HH24:MI:SS"

# source /Users/thenno/.yql/shell_completion
source /Users/thenno/.ya.completion/zsh/arc

export PATH="/opt/homebrew/bin:$PATH"
export HOMEBREW_NO_EMOJI=True
