export PATH="/opt/homebrew/bin:$PATH"
export HOMEBREW_NO_EMOJI=True

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi


if [ ! -d "$HOME/.pip" ] ; then
    mkdir -p $HOME/.pip
fi
PYTHONPATH="./.pip:$PYTHONPATH"
